version: 2
updates:
  - package-ecosystem: "npm"
    # El frontend usa pnpm, pero Dependabot usa el ecosistema npm para lockfiles de pnpm
    directory: "/btc-dashboard-frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "frontend"
    insecure-external-code-execution: "deny"

  - package-ecosystem: "pip"
    directory: "/btc-dashboard-backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "backend"
    insecure-external-code-execution: "deny"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "ci"
